development:
  adapter: postgresql
  encoding: unicode
  database: mass_health_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mass_health_test
  pool: 5
  username:
  password: